name: Publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

# Disable permissions for all of the available permissions
permissions: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@900f2210b1d28bbbd0bd22d17926b9e224e8f231
      - name: Copy on publish
        run: ./copy_on_publish.sh
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@7112915a1a834881d4c98ef7af12f3456e5c79c7
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: false
