name: Remove label when issue is closed
on:
  issues:
    types:
      - closed

permissions:
  contents: read

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    steps:
      - name: remove label
        run: gh issue edit "$ISSUE_NUMBER" --remove-label 'await triage'